openapi: 3.0.3
info:
  title: OpenAPI CDK Typescript Generator Basic Sample API
  description: OpenAPI CDK Typescript Generator Basic Sample API
  version: 1.0.0
tags:
  - name: Tests
    description: Some simple functions to test the generator
paths:
  /test:
    get:
      operationId: getAllTestObjects
      tags:
        - Test
      description: Get some test values
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TestObject'
    post:
      tags:
        - Test
      operationId: createTestObject
      description: Create new test value
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TestObject'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TestObject'
components:
  schemas:
    TestObject:
      type: object
      required:
        - bar
      properties:
        foo:
          type: string
        bar:
          type: number